### ISSUE TITLE
Apple silicon M1 support

### ISSUE THREAD

**Issue by Muzosh** [BitBoxSwiss/bitbox-wallet-app#1266]
Hello,

I'm just wondering, is Universal/Native binary on the roadmap or at least in considerations?

Thanks,
Muzosh

**Comment by thisconnect** [comment]
yes sorry 😇

**Comment by benma** [comment]
@pdr2002 is there any specific issue you are having with the current BitBoxApp build?

**Comment by tobomobo** [comment]
@benma 

Is it possible to get an update on this? My brother and I had some issues with rosetta2 and phantom battery drain on our m1 MacBooks and to remove it we had to reset our macs. We therefore are unable to install non-native software, including the bitbox wallet app. In addition to that, it's an extra attack vector because you are essentially and voluntarily opening your machine up to all old (x86) malware.

The Bitbox app is the last non-native thing we use, and therefore it is simply not worth the above-mentioned tradeoffs. 

Please update asap, it shouldn't be that hard anymore.

**Comment by benma** [comment]
@tobomobo no update yet. A comment above mentions that an upgrade to Qt 6 is needed for M1 support (at least, possibly more). We build the app with Qt 5.15 so we can keep supporting macOS 10.13, which is still in use (Qt 6 drops support for this platform). Making an universal binary using Qt 5.15 is not trivial unfortunately, as QtWebEngine for M1 doesn't seem to be  officially supported, see [here](https://bugreports.qt.io/browse/QTBUG-85279?focusedCommentId=562355&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-562355).

**Comment by tobomobo** [comment]
@benma 

Thanks for the prompt, albeit disappointing answer. 

I have no insight in your usage statistics, but I can't imagine that macOS 10.13 (originally released in 2017) is more important than the future of the whole platform. Security minded people, such as a bitbox02 customer, will certainly not stay on a five-year-old OS that doesn't get updates.

If the decision were up to me, I would abandon 10.13 immediately and I would then try to build a universal or native binary asap.

**Comment by pdr2002** [comment]
I totally agree 👍🏻
please urgently provide a Apple Sillicon native version, intel is history.

**Comment by tobomobo** [comment]
> I totally agree 👍🏻
> please urgently provide a Apple Sillicon native version, intel is history.

I wouldn’t say intel is history, but certainly 10.13 is. 
The future of the platform is more important than a single old version of the OS. 

Time to sunset 10.13 if it’s hindering progress in any way.

**Comment by benma** [comment]
Is it possible to enable Rosetta2 only for specific apps like the BitBoxApp? 

I am afraid sunsetting 10.13 is out of the question, as it would prevent some users from accessing their funds that are stuck with 10.13 still. There are even customers that cannot use the BitBoxApp because they are stuck with 10.12.

A possible way forward is to provide a universal binary for 10.14+ (including M1) and a separate release for 10.13. It complicates the build process, so there is no ETA.

**Comment by tobomobo** [comment]
> Is it possible to enable Rosetta2 only for specific apps like the BitBoxApp?
> 
> I am afraid sunsetting 10.13 is out of the question, as it would prevent some users from accessing their funds that are stuck with 10.13 still. There are even customers that cannot use the BitBoxApp because they are stuck with 10.12.
> 
> A possible way forward is to provide a universal binary for 10.14+ (including M1) and a separate release for 10.13. It complicates the build and release process, so there is no ETA.

Yes, technically it is possible to switch between Rosetta2 mode and Apple Silicon mode on a per app basis, but before that, you have to install it. Installing Rosetta is not an option for me unfortunately, due to the bugs I encountered and the inherent security risks. 

Additionally, once Rosetta is installed, it can't be removed.
I am certainly not the only who would rather keep it off my machine.


As for the people you mentioned. Wouldn't they still be able to use a previous release of your software? They don't seem to mind using old software... And the private keys are stored on the secure element anyway.

**Comment by pdr2002** [comment]
> 
ONCE activated Rosetta 2 will always  run in the background. ANY Intel only Program will be executed.

**Comment by benma** [comment]
@tobomobo this is very helpful, thanks a lot!

**Comment by benma** [comment]
Hi @d0minikh. No news as of yet. We'd first need to upgrade from Qt 5.15 to At 6.2+.

**Comment by d0minikh** [comment]
Hi @benma, thanks for the update!

**Comment by pdr2002** [comment]
> Hi @d0minikh. No news as of yet. We'd first need to upgrade from Qt 5.15 to At 6.2+.

You are telling that for nearly 2 years now, very disappointing. When do you actually DO IT? Your software is a security risk for my computer, and I'm not willing to take that chance much longer.  When will you provide security for all of your users?

**Comment by jingx23** [comment]
Any updates on this? We already on M3 so would be time to have the App running without Rosetta mode :).

**Comment by benma** [comment]
As mentioned earlier in this issue, we are kind of blocked here because Qt does support universal builds in version 5.15, only in Qt 6, but we can't use Qt 6 as this version drops support for older Windows/macOS/Linux versions still used by BitBoxApp users last time we looked into it.

It seems that Qt backported universal builds to 5.15.9, but unfortunately without QtWebEngine, which we require:

https://code.qt.io/cgit/qt/qtreleasenotes.git/about/qt/5.15.9/release-note.md

The alternatives now are:

- officially drop support for the older OS versions, upgrade Qt, and release universal builds 
  - we will consider it, but we want to avoid imposing this major annoyance on our users if many of them are stuck on old OSs for whatever reason 
- revisit again in the future once the older OS versions are dead for good

I left out the possibility of us releasing two separate versions for macOS, as this is not really feasible for us to do.

**Comment by lclc** [comment]
Maybe a good idea to in general communicate for how long which Operating
Systems releases are officially supported.

**Comment by Muzosh** [comment]
@benma As an author of this issue/thread, I just want to acknowledge that I understand your situation and I'm fine for waiting until your number of users with old OS drops.

We, AppleSilicon users, still do have Rosetta available and for me personally, there are no issues, bugs or performance drops. Wide availability of an app operating with cold crypto wallet is justifiable for the cost of _very_ minor annoyance.

**Comment by pdr2002** [comment]
That means, you want told many people hostage, who cannot use this version for security reasons? What about a new version with QT6 and the people of the old version still can use the old one. If they want the new version, they would have tu update their OS. For the old Version, you only need to provide security fixes. If they want new features, update.
Why are we less worth, than other Users?

Freundliche Grüße / Kind Regards

Peter

please don't print this e-mail unless you really need to 🌳🌲☘️💐🌸
Am 18. Jan. 2024, 12:00 +0100 schrieb benma ***@***.***>:

**Comment by benma** [comment]
> What about a new version with QT6 and the people of the old version still can use the old one. 

As I mentioned in my previous comment, supporting two separate releases (including backporting fixes) is not feasible for us to do at the moment.

Users are not worth less than other users - it is simply a trade-off. I am sorry that not everybody can be made happy, but we are trying our best.

**Comment by d0minikh** [comment]
I would recommend to align with the official Apple Supported operating systems.
Since older versions not getting any kind of security update, why supporting them instead of new more secure systems and/or architectures?
Apple supports always the three latest operating systems. [Wiki List](https://en.wikipedia.org/wiki/MacOS#Timeline_of_releases)

Your product is very security focused, it doesn't make sense to me to argue more users run unsupported and not secure OS versions than supported versions. That makes the software more vulnerable to attacks, as the operating system itself is already less secure. Maybe you should consider to advertise this and educate users to have a better update behaviour then excluding users that have the latest software and don't want to do code migrations with rosetta 2.

**Comment by marc-cgn** [comment]
Think we all have good reasons for choosing bitbox. Apple introduced the M1 on 10.11.2020. Today it`s May 1st 2024 an Bitbox is still not supporting this new architecture. Rosetta2 is just a timeboxed solution until the dev teams get their work done. I now bought a Pixel Android to use my bitbox. So as of know I cannot state any longer, that bitbox ist supporting Apple. Take my unsatisfaction on this after 3,5 years of doing nothing.

**Comment by pdr2002** [comment]
I couldn’t agree more, I will Switch to BlueWallet on my iPhone today, I waited long enough. Very disappointed.
Peter

please don't print this e-mail unless you really need to
Am 1. Mai 2024, 12:02 +0200 schrieb Marc ***@***.***>:

**Comment by benma** [comment]
PR: https://github.com/BitBoxSwiss/bitbox-wallet-app/pull/3010

**Comment by benma** [comment]
The above PR was merged and tested. The next BitBoxApp release for macOS will be a universal build supporting both arm64 and amd64.
